config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations'
  }
  resources :users, only: [:edit, :update]
  resources :legislators, only: :index
  resources :messages, only: [:new, :edit, :create]
  get 'messages/address', as: :message_address, defaults: { format: :json }
  root 'messages#new', as: :home
end

app/models/message.rb
class Message < ActiveRecord::Base
  include ActiveModel::Validations
  has_and_belongs_to_many :legislators
  validates_presence_of :subject, :body, :name, :email, :address_line, :city, :state, :zip

  class << self
    def form_topics
      Legislators::Email.user_options
    end
  end

  def send_email
    @emails = legislators.map do |l|
      email = Legislators::EmailForm.new self, l
      email.fillout_and_send
      email
    end
  end

  def sent?
    captchas.empty? && @emails.select{ |e| e.sent? }.any?
  end

  def captchas
    return [] unless @emails
    @emails.map{ |e| e.captcha }.compact
  end

  def first_name
    parsed_name&.first
  end

  def last_name
    parsed_name&.last
  end

  def address
    @address ||= Address.new line: address_line, city: city, state: state, zip: zip
  end

private

  def parsed_name
    @parsed_name = HumanNameParser.parse name
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user_address
  layout 'message'

  def new
    render_message
  end

  def edit
    render_message message: Message.find(params[:id])
  end

  def create
    @message = Message.new message_params
    if @message.save
      @message.send_email
      if @message.sent?
        thank_you_page
      elsif @message.captchas.any?
        binding.pry
      else
        error_page
      end
    else
      render_message(@message)
    end
  end

  def error_page(errors=false)
    render 'message/error'
  end

  def thank_you_page
    render 'messages/thank_you'
  end

  def address
    a = message_params
    a[:line] = a.delete :address_line
    address = Address.new a

    if address.valid?
      legislators = address.legislators
      if legislators.length > 0
        return render json: {
            data: legislators.to_json,
            html: render_to_string(partial: 'messages/legislator', layout: false, collection: legislators)
          },
          status: 200
      end
    end

    render json: { errors: @model.errors.full_messages }
  end

private

  def message_params
    pars = params.require(:message).permit :name, :email, :address_line, :city, :state, :zip, :subject, :body, :legislator_ids
    pars[:legislator_ids] = pars[:legislator_ids].split(',') if pars[:legislator_ids]
    pars
  end

  def render_message(message: nil)
    @user = current_user || User.new
    @user.address || @user.build_address
    message ||= @user.messages.build
    @message = message
    @legislators = @user.legislators.reject{ |l| %w{trump pence}.include? l.last_name.downcase }
  end

  def require_user_address
    if current_user.present? && current_user.address.blank?
      redirect_to edit_user_path current_user
    end
  end
end

app/helpers/message_helper.rb
module MessageHelper
  def defaults
    @defaults = {
      name: current_user&.name,
      email: current_user&.email,
      address_line: current_user&.address&.line,
      city: current_user&.address&.city,
      state: current_user&.address&.state,
      zip: current_user&.address&.zip,
      subject: nil,
      body: nil
    }
  end
end

app/views/messages/_error.slim
p We're sorry, we were unable to send your message

app/views/messages/_form.slim
= form_for @message do |message|
  - d = defaults
  .legislator_container
    h3 Who would you like to contact

    .field.hidden
      = message.text_field :legislator_ids, class: 'legislator_ids hidden', value: @legislators.map{ |l| l.id }.join(',')

    .legislators

      = render partial: 'messages/legislator', collection: @legislators, as: :legislator

  .user_info
    .field
      = message.text_field :name, class: 'name', value: d[:name], placeholder: true

    .field
      = message.email_field :email, class: 'email', value: d[:email], placeholder: true

    .address
      .field
        = message.text_field :address_line, value: d[:address_line], placeholder: 'Address'

      .field
        = message.text_field :city, value: d[:city], placeholder: true

      .field
        = message.select :state, States::Array, prompt: 'State', selected: d[:state], include_blank: 'State'

      .field
        = message.text_field :zip, value: d[:zip], placeholder: true

  .body_section
    .field
      = message.select :subject, Message.form_topics, include_blank: 'Pick a Topic'

    .field
      = message.text_area :body, value: d[:body], placeholder: true

    = message.submit

app/views/messages/_legislator.slim
div[
  class = "legislator #{legislator.name.downcase.gsub(' ', '_')} #{legislator.party.downcase}"
  data-id = legislator.id
]
  figure
    = image_tag asset_path "legislators/#{legislator.image_name}"

  .info
    .name = legislator.name
    .position = legislator.position_long.capitalize

app/views/messages/_new_edit.slim
.message_container.container
  .message_form
    = render partial: 'messages/form'

  .template_container style="min-width: 30px;"

app/views/messages/edit.slim
= render partial: 'new_edit'

app/views/messages/new.slim
= render partial: 'new_edit'

app/views/messages/thank_you.slim
p Thank you for writing to your legislators!
= link_to 'white another letter', new_message_path